import type { Octokit } from "@octokit/rest";
import { githubRateLimiter } from "../utils/rateLimiter";
import { logger } from "../utils/logger";
import type { GitHubReviewComment, GitHubReviewSubmission } from "./types";
import type { ReviewComment } from "../review/types";

/** Emoji mapping for severity levels */
const SEVERITY_EMOJI: Record<string, string> = {
  critical: "🔴",
  warning: "🟡",
  suggestion: "🔵",
  praise: "🟢",
};

/** Emoji mapping for categories */
const CATEGORY_EMOJI: Record<string, string> = {
  bug: "🐛",
  security: "🔒",
  performance: "⚡",
  readability: "📖",
  architecture: "🏗️",
  "best-practice": "✅",
};

/**
 * Formats a single review comment into a markdown body for GitHub.
 */
export function formatCommentBody(comment: ReviewComment): string {
  const severityEmoji = SEVERITY_EMOJI[comment.severity] ?? "💬";
  const categoryEmoji = CATEGORY_EMOJI[comment.category] ?? "📝";
  const severityLabel =
    comment.severity.charAt(0).toUpperCase() + comment.severity.slice(1);
  const categoryLabel =
    comment.category.charAt(0).toUpperCase() + comment.category.slice(1);

  let body = `### ${severityEmoji} ${severityLabel} — ${categoryEmoji} ${categoryLabel}\n\n`;
  body += `${comment.comment}\n`;

  if (comment.suggestion) {
    body += `\n${comment.suggestion}\n`;
  }

  return body;
}

/**
 * Generates the review summary body that appears at the top of the review.
 */
export function generateReviewSummary(
  comments: ReviewComment[],
  filesReviewed: number,
  filesSkipped: number
): string {
  const criticalCount = comments.filter(
    (c) => c.severity === "critical"
  ).length;
  const warningCount = comments.filter(
    (c) => c.severity === "warning"
  ).length;
  const suggestionCount = comments.filter(
    (c) => c.severity === "suggestion"
  ).length;
  const praiseCount = comments.filter(
    (c) => c.severity === "praise"
  ).length;

  const totalIssues = criticalCount + warningCount + suggestionCount;

  let summary = `## 🤖 AI Code Review Summary\n\n`;
  summary += `| Metric | Count |\n`;
  summary += `|--------|-------|\n`;
  summary += `| 📁 Files reviewed | ${filesReviewed} |\n`;
  summary += `| 📁 Files skipped | ${filesSkipped} |\n`;
  summary += `| 🔴 Critical | ${criticalCount} |\n`;
  summary += `| 🟡 Warning | ${warningCount} |\n`;
  summary += `| 🔵 Suggestion | ${suggestionCount} |\n`;
  summary += `| 🟢 Praise | ${praiseCount} |\n`;
  summary += `| **Total comments** | **${comments.length}** |\n\n`;

  // Overall assessment
  if (criticalCount > 0) {
    summary += `### ⚠️ Overall Assessment\n`;
    summary += `Found **${criticalCount} critical issue(s)** that should be addressed before merging.\n\n`;
  } else if (warningCount > 0) {
    summary += `### 📋 Overall Assessment\n`;
    summary += `No critical issues found. There are **${warningCount} warning(s)** worth reviewing.\n\n`;
  } else if (totalIssues === 0 && praiseCount > 0) {
    summary += `### ✨ Overall Assessment\n`;
    summary += `Great work! The code looks clean and well-written. 🎉\n\n`;
  } else {
    summary += `### 👍 Overall Assessment\n`;
    summary += `The code changes look reasonable with only minor suggestions.\n\n`;
  }

  summary += `---\n`;
  summary += `> 🤖 *This review was generated by AI PR Reviewer. `;
  summary += `Please use your judgment when applying suggestions.*\n`;

  return summary;
}

/**
 * Maps parsed AI review comments to the GitHub review comment format.
 * Filters out comments whose line numbers don't map to valid diff positions.
 */
export function mapToGitHubComments(
  comments: ReviewComment[]
): GitHubReviewComment[] {
  return comments
    .filter((comment) => comment.line > 0 && comment.file.length > 0)
    .map((comment) => ({
      path: comment.file,
      line: comment.line,
      side: "RIGHT" as const,
      body: formatCommentBody(comment),
    }));
}

/**
 * Posts a complete PR review with inline comments and a summary.
 *
 * Uses the GitHub "create review" API to post all comments atomically
 * as a single review rather than individual comments.
 */
export async function postReview(
  octokit: Octokit,
  submission: GitHubReviewSubmission
): Promise<void> {
  const {
    owner,
    repo,
    pullNumber,
    event,
    body,
    comments,
    commitId,
  } = submission;

  const prLogger = logger.child({ owner, repo, pullNumber });

  try {
    await githubRateLimiter.acquire();

    // GitHub has a limit of ~50 comments per review submission.
    // If we have more, we need to split into multiple reviews.
    const MAX_COMMENTS_PER_REVIEW = 50;

    if (comments.length <= MAX_COMMENTS_PER_REVIEW) {
      // Single review submission
      await octokit.pulls.createReview({
        owner,
        repo,
        pull_number: pullNumber,
        commit_id: commitId,
        event,
        body,
        comments: comments.map((c) => ({
          path: c.path,
          line: c.line,
          side: c.side,
          body: c.body,
        })),
      });

      githubRateLimiter.resetRetries();

      prLogger.info(
        { commentCount: comments.length, event },
        "Posted PR review successfully"
      );
    } else {
      // Split into batches: first batch gets the summary, rest are COMMENT events
      const batches: GitHubReviewComment[][] = [];
      for (let i = 0; i < comments.length; i += MAX_COMMENTS_PER_REVIEW) {
        batches.push(comments.slice(i, i + MAX_COMMENTS_PER_REVIEW));
      }

      for (let i = 0; i < batches.length; i++) {
        const batch = batches[i];
        if (!batch) continue;

        await githubRateLimiter.acquire();

        const isFirstBatch = i === 0;
        const isLastBatch = i === batches.length - 1;

        await octokit.pulls.createReview({
          owner,
          repo,
          pull_number: pullNumber,
          commit_id: commitId,
          // Only the last batch triggers the review event
          event: isLastBatch ? event : "COMMENT",
          body: isFirstBatch ? body : `*(Continued — batch ${i + 1}/${batches.length})*`,
          comments: batch.map((c) => ({
            path: c.path,
            line: c.line,
            side: c.side,
            body: c.body,
          })),
        });

        githubRateLimiter.resetRetries();

        prLogger.info(
          {
            batch: i + 1,
            totalBatches: batches.length,
            batchSize: batch.length,
          },
          "Posted review batch"
        );
      }

      prLogger.info(
        { totalComments: comments.length, batches: batches.length },
        "Posted all review batches successfully"
      );
    }
  } catch (error) {
    const err = error as { status?: number; message?: string };

    // Handle specific GitHub API errors
    if (err.status === 422) {
      prLogger.warn(
        { error: err.message },
        "GitHub rejected review — likely invalid line numbers. Posting summary only."
      );

      // Fallback: post just the summary without inline comments
      try {
        await githubRateLimiter.acquire();
        await octokit.pulls.createReview({
          owner,
          repo,
          pull_number: pullNumber,
          commit_id: commitId,
          event: "COMMENT",
          body:
            body +
            "\n\n> ⚠️ *Some inline comments could not be posted due to line number mapping issues.*",
          comments: [],
        });
        githubRateLimiter.resetRetries();
        prLogger.info("Posted review summary without inline comments (fallback)");
      } catch (fallbackError) {
        prLogger.error({ error: fallbackError }, "Failed to post fallback review summary");
        throw fallbackError;
      }
    } else {
      throw error;
    }
  }
}

/**
 * Posts a simple comment on a PR (not a review, just a standalone comment).
 * Used for error notifications or status updates.
 */
export async function postPRComment(
  octokit: Octokit,
  owner: string,
  repo: string,
  pullNumber: number,
  body: string
): Promise<void> {
  await githubRateLimiter.acquire();

  await octokit.issues.createComment({
    owner,
    repo,
    issue_number: pullNumber,
    body,
  });

  githubRateLimiter.resetRetries();

  logger.info(
    { owner, repo, pullNumber },
    "Posted standalone PR comment"
  );
}